# -*- coding: utf-8 -*-
"""aula-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xtjJzSyaESmyY3OIE3goR-SbwbSqSbuq
"""

# idade = 28
# nome = 'Alex'
# altura = 1.75

# print('Nome: ', nome)
# print('Idade: ', idade)
# print('Altura: ', altura)

#1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.

# n1 = int(input("Digite o primeiro valor: "))
# print('O quadrado do número é: ',n1*n1)

# 2 - Crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.

# primeiro_nome = input('Digite seu primeiro nome: ')
# sobrenome = input('Digite seu sobrenome: ')
# print(primeiro_nome, sobrenome)

# 3 - Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.

# number1 = input('Digite o primeiro número inteiro: ') #n1 = 5 / n1= '5'
# number2 = input('Digite o segundo número inteiro: ')
# print('O número concatenado é: ', number1+number2)

# 4 - Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.

# linguagem = 'Python'
# number3 = input('Digite o segundo número inteiro: ')
# print(linguagem + number3)

# 5 -Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

# frase = 'Estamos no curso de programação em python'
# palavra = input('Digite uma palavra: ')
# print(frase,palavra)

# 6 - Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".

# horas = '11'
# minutos = '25'
# segundos = '45'

# print(horas+':'+minutos+':'+segundos)

# 7 - Declare duas variáveis com números de telefone, incluindo um código de área e o número principal. Concatene esses valores para formar um número de telefone completo.

# cda = '11'
# telefone ='970688477'
# print(cda+'-'+telefone)

# 8 - Crie uma lista de ingredientes para uma receita. Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.

# ingrediente1 = '2 ovos'
# ingrediente2 = '200g de farinho de trigo'
# ingrediente3 = '2 xicara de fermento'
# ingrediente4 = '1 litro de leite'
# ingrediente5 = '6 colheres de chocolate em pó'

# print('Para fazer um bolo de chocolate, vai os seguintes ingredientes:',ingrediente1+',',ingrediente2+',',ingrediente3+',',ingrediente4+',',ingrediente5)

# 9 - Peça ao usuário para digitar três adjetivos e armazene-os em variáveis. Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.

# adj1 = input('Cite três adjetivos essenciais para se tornar um profissional de TI, primeiro: ')
# adj2 = input('Cite três adjetivos essenciais para se tornar um profissional de TI, segundo: ')
# adj3 = input('Cite três adjetivos essenciais para se tornar um profissional de TI, terceiro: ')

# print('Em um mundo onde a tecnologia da informação evolui rapidamente, a abordagem do', adj1, 'a',  adj2, 'e a', adj3, 'são três adjetivos essenciais para se tornar um profissional competente e inovador.')


#------------------------------------------


# a = 10
# b = 20
# if(a > b): # Se
#     print('É maior') #true

# # elif():   # Se 2...
# #   print()

# else:       # Senão
#     print('É menor') #false

